//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DecisionPointEntities : DbContext
    {
        public DecisionPointEntities()
            : base("name=DecisionPointEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DP_AdditionalReqAck> DP_AdditionalReqAck { get; set; }
        public DbSet<DP_AdditionalReqMapping> DP_AdditionalReqMapping { get; set; }
        public DbSet<DP_AdditionalReqMaster> DP_AdditionalReqMaster { get; set; }
        public DbSet<DP_AdditionalReqUploadDocs> DP_AdditionalReqUploadDocs { get; set; }
        public DbSet<DP_Announcement> DP_Announcement { get; set; }
        public DbSet<DP_APILog> DP_APILog { get; set; }
        public DbSet<DP_APIMapping> DP_APIMapping { get; set; }
        public DbSet<DP_APIMaster> DP_APIMaster { get; set; }
        public DbSet<DP_APIRoleTypeMaster> DP_APIRoleTypeMaster { get; set; }
        public DbSet<DP_BackgroundDocUpload> DP_BackgroundDocUpload { get; set; }
        public DbSet<DP_BackGroundMapping> DP_BackGroundMapping { get; set; }
        public DbSet<DP_BGCheckDetailMapping> DP_BGCheckDetailMapping { get; set; }
        public DbSet<DP_BGCheckMapping> DP_BGCheckMapping { get; set; }
        public DbSet<DP_BGCheckMaster> DP_BGCheckMaster { get; set; }
        public DbSet<DP_BGCheckPackageDetailMaster> DP_BGCheckPackageDetailMaster { get; set; }
        public DbSet<DP_BGCheckPackageMaster> DP_BGCheckPackageMaster { get; set; }
        public DbSet<DP_BusinessClasses> DP_BusinessClasses { get; set; }
        public DbSet<DP_Category> DP_Category { get; set; }
        public DbSet<DP_City> DP_City { get; set; }
        public DbSet<DP_CityMapping> DP_CityMapping { get; set; }
        public DbSet<DP_CitysTest> DP_CitysTest { get; set; }
        public DbSet<DP_ClientMapping> DP_ClientMapping { get; set; }
        public DbSet<DP_ClientMaster> DP_ClientMaster { get; set; }
        public DbSet<DP_ComapnyVendorMapping> DP_ComapnyVendorMapping { get; set; }
        public DbSet<DP_CommAnswers> DP_CommAnswers { get; set; }
        public DbSet<DP_CommAssesment> DP_CommAssesment { get; set; }
        public DbSet<DP_CommAsstAnswer> DP_CommAsstAnswer { get; set; }
        public DbSet<Dp_CommAsstAtempts> Dp_CommAsstAtempts { get; set; }
        public DbSet<DP_CommContents> DP_CommContents { get; set; }
        public DbSet<DP_CommContentViewTime> DP_CommContentViewTime { get; set; }
        public DbSet<DP_CommDocSpentTime> DP_CommDocSpentTime { get; set; }
        public DbSet<DP_CommLinks> DP_CommLinks { get; set; }
        public DbSet<DP_CommRecipientFilter> DP_CommRecipientFilter { get; set; }
        public DbSet<DP_CommRquiredActions> DP_CommRquiredActions { get; set; }
        public DbSet<DP_CommTestRules> DP_CommTestRules { get; set; }
        public DbSet<DP_CompanyPayment> DP_CompanyPayment { get; set; }
        public DbSet<DP_CompanyStaffMapping> DP_CompanyStaffMapping { get; set; }
        public DbSet<DP_ConfigurationSetting> DP_ConfigurationSetting { get; set; }
        public DbSet<DP_ContractEvent> DP_ContractEvent { get; set; }
        public DbSet<DP_ContractEventsMailLog> DP_ContractEventsMailLog { get; set; }
        public DbSet<DP_ContractMailReminderLog> DP_ContractMailReminderLog { get; set; }
        public DbSet<DP_ContractMaster> DP_ContractMaster { get; set; }
        public DbSet<DP_County> DP_County { get; set; }
        public DbSet<DP_CountyMapping> DP_CountyMapping { get; set; }
        public DbSet<DP_CreateContractDocMaster> DP_CreateContractDocMaster { get; set; }
        public DbSet<DP_CreateContractMaster> DP_CreateContractMaster { get; set; }
        public DbSet<DP_CreateContractServiceMaster> DP_CreateContractServiceMaster { get; set; }
        public DbSet<DP_DefaultPaymentMaster> DP_DefaultPaymentMaster { get; set; }
        public DbSet<DP_DescendentMapping> DP_DescendentMapping { get; set; }
        public DbSet<DP_DocFlow> DP_DocFlow { get; set; }
        public DbSet<DP_DocFlowMapping> DP_DocFlowMapping { get; set; }
        public DbSet<DP_DocumentDetails> DP_DocumentDetails { get; set; }
        public DbSet<DP_DocumentMailLog> DP_DocumentMailLog { get; set; }
        public DbSet<DP_EmailAccount> DP_EmailAccount { get; set; }
        public DbSet<DP_EmailTemplate> DP_EmailTemplate { get; set; }
        public DbSet<DP_EmailTokens> DP_EmailTokens { get; set; }
        public DbSet<DP_EmailTrakingDetails> DP_EmailTrakingDetails { get; set; }
        public DbSet<DP_FlowMapping> DP_FlowMapping { get; set; }
        public DbSet<DP_FlowMaster> DP_FlowMaster { get; set; }
        public DbSet<DP_Group> DP_Group { get; set; }
        public DbSet<DP_GuideInstructions> DP_GuideInstructions { get; set; }
        public DbSet<DP_ICClientsPermissionMaster> DP_ICClientsPermissionMaster { get; set; }
        public DbSet<DP_ICNonClientsMapping> DP_ICNonClientsMapping { get; set; }
        public DbSet<DP_ICNonClientsPaymentLog> DP_ICNonClientsPaymentLog { get; set; }
        public DbSet<DP_ICPaymentMapping> DP_ICPaymentMapping { get; set; }
        public DbSet<DP_InsuranceAck> DP_InsuranceAck { get; set; }
        public DbSet<DP_InsuranceMapping> DP_InsuranceMapping { get; set; }
        public DbSet<DP_InsuranceMaster> DP_InsuranceMaster { get; set; }
        public DbSet<DP_InsuranceUploadDocs> DP_InsuranceUploadDocs { get; set; }
        public DbSet<DP_Invitation> DP_Invitation { get; set; }
        public DbSet<DP_License> DP_License { get; set; }
        public DbSet<DP_LicenseInsuranceAck> DP_LicenseInsuranceAck { get; set; }
        public DbSet<DP_LicenseInsuranceDocUpload> DP_LicenseInsuranceDocUpload { get; set; }
        public DbSet<DP_LicenseInsuranceMaster> DP_LicenseInsuranceMaster { get; set; }
        public DbSet<DP_LicenseInsuranceReceiver> DP_LicenseInsuranceReceiver { get; set; }
        public DbSet<DP_LicenseInsuranceVendorType> DP_LicenseInsuranceVendorType { get; set; }
        public DbSet<DP_MailFooter> DP_MailFooter { get; set; }
        public DbSet<DP_PayementMaster> DP_PayementMaster { get; set; }
        public DbSet<DP_PaymentFlowMaster> DP_PaymentFlowMaster { get; set; }
        public DbSet<DP_Performance> DP_Performance { get; set; }
        public DbSet<DP_PermissionMapping> DP_PermissionMapping { get; set; }
        public DbSet<DP_PermissionMaster> DP_PermissionMaster { get; set; }
        public DbSet<DP_PermissionTableMapping> DP_PermissionTableMapping { get; set; }
        public DbSet<DP_PermissionTableMaster> DP_PermissionTableMaster { get; set; }
        public DbSet<Dp_ProfessionalLicenseAck> Dp_ProfessionalLicenseAck { get; set; }
        public DbSet<DP_ProfessionalLicenseMapping> DP_ProfessionalLicenseMapping { get; set; }
        public DbSet<DP_ProfessionalLicenseMaster> DP_ProfessionalLicenseMaster { get; set; }
        public DbSet<DP_ProfessionalLicenseUploadDocs> DP_ProfessionalLicenseUploadDocs { get; set; }
        public DbSet<DP_Profile> DP_Profile { get; set; }
        public DbSet<DP_Recipient> DP_Recipient { get; set; }
        public DbSet<DP_RecurringPayment> DP_RecurringPayment { get; set; }
        public DbSet<DP_RecurringPaymentTransaction> DP_RecurringPaymentTransaction { get; set; }
        public DbSet<DP_Reference> DP_Reference { get; set; }
        public DbSet<DP_ReportLog> DP_ReportLog { get; set; }
        public DbSet<DP_ReqDocAck> DP_ReqDocAck { get; set; }
        public DbSet<DP_ReqDocAudit> DP_ReqDocAudit { get; set; }
        public DbSet<DP_ReqDocAuditUpload> DP_ReqDocAuditUpload { get; set; }
        public DbSet<DP_ReqDocReceiver> DP_ReqDocReceiver { get; set; }
        public DbSet<DP_ReqDocSender> DP_ReqDocSender { get; set; }
        public DbSet<DP_ReqDocService> DP_ReqDocService { get; set; }
        public DbSet<DP_ReqDocUpload> DP_ReqDocUpload { get; set; }
        public DbSet<DP_ReqDocVendorType> DP_ReqDocVendorType { get; set; }
        public DbSet<DP_RoleMapping> DP_RoleMapping { get; set; }
        public DbSet<DP_RoleMaster> DP_RoleMaster { get; set; }
        public DbSet<DP_Security> DP_Security { get; set; }
        public DbSet<DP_ServiceMapping> DP_ServiceMapping { get; set; }
        public DbSet<DP_ServicesMaster> DP_ServicesMaster { get; set; }
        public DbSet<DP_ServiceTranslationTable> DP_ServiceTranslationTable { get; set; }
        public DbSet<DP_SiteUrl> DP_SiteUrl { get; set; }
        public DbSet<DP_SkillSetMapping> DP_SkillSetMapping { get; set; }
        public DbSet<DP_SkillSetMaster> DP_SkillSetMaster { get; set; }
        public DbSet<DP_State> DP_State { get; set; }
        public DbSet<DP_StateMapping> DP_StateMapping { get; set; }
        public DbSet<DP_SterlingReqResMaster> DP_SterlingReqResMaster { get; set; }
        public DbSet<DP_SterlingScreeningMapping> DP_SterlingScreeningMapping { get; set; }
        public DbSet<DP_SuperAdminLogin> DP_SuperAdminLogin { get; set; }
        public DbSet<DP_TabMaster> DP_TabMaster { get; set; }
        public DbSet<DP_TitleMapping> DP_TitleMapping { get; set; }
        public DbSet<DP_TitleMaster> DP_TitleMaster { get; set; }
        public DbSet<DP_User> DP_User { get; set; }
        public DbSet<DP_UserDocContentStatus> DP_UserDocContentStatus { get; set; }
        public DbSet<DP_VendorType> DP_VendorType { get; set; }
        public DbSet<DP_VendorTypeMapping> DP_VendorTypeMapping { get; set; }
        public DbSet<DP_VerfiedLicenseDetails> DP_VerfiedLicenseDetails { get; set; }
        public DbSet<DP_WebinarOrganiserMaster> DP_WebinarOrganiserMaster { get; set; }
        public DbSet<DP_Welcome> DP_Welcome { get; set; }
        public DbSet<DP_ZipCode> DP_ZipCode { get; set; }
        public DbSet<DP_ZipMapping> DP_ZipMapping { get; set; }
        public DbSet<DP_ZipTest> DP_ZipTest { get; set; }
        public DbSet<StateAndCity> StateAndCity { get; set; }
    
        public virtual ObjectResult<USP_GetUserDetail_Result> USP_GetUserDetail(string companyId, Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo)
        {
            var companyIdParameter = companyId != null ?
                new ObjectParameter("companyId", companyId) :
                new ObjectParameter("companyId", typeof(string));
    
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("dateFrom", dateFrom) :
                new ObjectParameter("dateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("dateTo", dateTo) :
                new ObjectParameter("dateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GetUserDetail_Result>("USP_GetUserDetail", companyIdParameter, dateFromParameter, dateToParameter);
        }
    
        public virtual ObjectResult<USP_UserView_Result> USP_UserView(Nullable<int> userID, Nullable<int> documentID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(int));
    
            var documentIDParameter = documentID.HasValue ?
                new ObjectParameter("documentID", documentID) :
                new ObjectParameter("documentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_UserView_Result>("USP_UserView", userIDParameter, documentIDParameter);
        }
    }
}
