//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_AdditionalReqMapping
    {
        public int Id { get; set; }
        public Nullable<int> AddReqId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CompanyId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool DocAndDataStatus { get; set; }
        public Nullable<System.DateTime> DocUploadedDate { get; set; }
    
        public virtual DP_AdditionalReqMaster DP_AdditionalReqMaster { get; set; }
    }
}
