//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_AdditionalReqMaster
    {
        public DP_AdditionalReqMaster()
        {
            this.DP_AdditionalReqAck = new HashSet<DP_AdditionalReqAck>();
            this.DP_AdditionalReqMapping = new HashSet<DP_AdditionalReqMapping>();
            this.DP_AdditionalReqUploadDocs = new HashSet<DP_AdditionalReqUploadDocs>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ICTypeId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CompanyId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string CreatorCompanyId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string UploadedBy { get; set; }
        public string Title { get; set; }
        public Nullable<int> Review { get; set; }
        public Nullable<bool> IsStaffTitle { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    
        public virtual ICollection<DP_AdditionalReqAck> DP_AdditionalReqAck { get; set; }
        public virtual ICollection<DP_AdditionalReqMapping> DP_AdditionalReqMapping { get; set; }
        public virtual ICollection<DP_AdditionalReqUploadDocs> DP_AdditionalReqUploadDocs { get; set; }
    }
}
