//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_BGCheckMapping
    {
        public DP_BGCheckMapping()
        {
            this.DP_BGCheckDetailMapping = new HashSet<DP_BGCheckDetailMapping>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CompanyId { get; set; }
        public Nullable<int> BGCheckId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string Source { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> StatusChangeDate { get; set; }
        public string SterlingOrderId { get; set; }
        public string LicenseNumber { get; set; }
        public string LicenseCountryCode { get; set; }
        public string LicenseStateCode { get; set; }
        public Nullable<System.DateTime> LicenseExpDate { get; set; }
        public Nullable<byte> RequirmentType { get; set; }
    
        public virtual ICollection<DP_BGCheckDetailMapping> DP_BGCheckDetailMapping { get; set; }
        public virtual DP_BGCheckMaster DP_BGCheckMaster { get; set; }
    }
}
