//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_BusinessClasses
    {
        public int Id { get; set; }
        public string BusinessClass { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
