//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_BGCheckMaster
    {
        public DP_BGCheckMaster()
        {
            this.DP_BGCheckMapping = new HashSet<DP_BGCheckMapping>();
        }
    
        public int Id { get; set; }
        public Nullable<int> BGCheckPkgId { get; set; }
        public Nullable<int> ICTypeId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CompanyId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatorCompanyId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ReqPkgByCompany { get; set; }
        public string Source { get; set; }
    
        public virtual ICollection<DP_BGCheckMapping> DP_BGCheckMapping { get; set; }
        public virtual DP_BGCheckPackageMaster DP_BGCheckPackageMaster { get; set; }
    }
}
