//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_BackGroundMapping
    {
        public DP_BackGroundMapping()
        {
            this.DP_BackgroundDocUpload = new HashSet<DP_BackgroundDocUpload>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CompanyId { get; set; }
        public Nullable<int> MasterId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Source { get; set; }
        public string CreatorName { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDNA { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    
        public virtual ICollection<DP_BackgroundDocUpload> DP_BackgroundDocUpload { get; set; }
    }
}
