//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_BGCheckDetailMapping
    {
        public int Id { get; set; }
        public Nullable<int> BGCheckPkgDetailId { get; set; }
        public string Status { get; set; }
        public Nullable<int> BGCheckMappingId { get; set; }
        public Nullable<System.DateTime> StatusChangeDate { get; set; }
    
        public virtual DP_BGCheckMapping DP_BGCheckMapping { get; set; }
        public virtual DP_BGCheckPackageDetailMaster DP_BGCheckPackageDetailMaster { get; set; }
    }
}
