//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_CommTestRules
    {
        public int Id { get; set; }
        public Nullable<bool> RandQues { get; set; }
        public Nullable<bool> RandAns { get; set; }
        public Nullable<bool> ReqReTest { get; set; }
        public string PassingScore { get; set; }
        public string Attempts { get; set; }
        public Nullable<bool> ShowWrongeAns { get; set; }
        public Nullable<int> DocId { get; set; }
        public string Instruction { get; set; }
    
        public virtual DP_DocumentDetails DP_DocumentDetails { get; set; }
    }
}
