//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_CommRecipientFilter
    {
        public int Id { get; set; }
        public string FilterType { get; set; }
        public string Filtervalue { get; set; }
        public Nullable<int> DocId { get; set; }
        public string DeliveredCompanyId { get; set; }
        public string CoverageArea { get; set; }
        public string OptionalVal { get; set; }
        public Nullable<byte> CoverageType { get; set; }
    
        public virtual DP_DocumentDetails DP_DocumentDetails { get; set; }
    }
}
