//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_County
    {
        public DP_County()
        {
            this.DP_City = new HashSet<DP_City>();
        }
    
        public int Id { get; set; }
        public Nullable<int> StateId { get; set; }
        public string County { get; set; }
        public string StateAbbre { get; set; }
    
        public virtual ICollection<DP_City> DP_City { get; set; }
        public virtual DP_State DP_State { get; set; }
    }
}
