//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_CommDocSpentTime
    {
        public int id { get; set; }
        public Nullable<int> Userid { get; set; }
        public Nullable<int> DocId { get; set; }
        public Nullable<long> SpendTime { get; set; }
        public Nullable<int> AdminId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ViewDate { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
