//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_ContractEvent
    {
        public int Id { get; set; }
        public Nullable<int> ContractId { get; set; }
        public string EventTitle { get; set; }
        public string Paragraph { get; set; }
        public string Section { get; set; }
        public string SubSection { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<int> EventReminderDay { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string AssignedUserIds { get; set; }
    
        public virtual DP_CreateContractMaster DP_CreateContractMaster { get; set; }
    }
}
