//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_City
    {
        public int Id { get; set; }
        public Nullable<int> StateId { get; set; }
        public int CountyId { get; set; }
        public string City { get; set; }
        public string StateAbbre { get; set; }
        public string CountyName { get; set; }
    
        public virtual DP_County DP_County { get; set; }
        public virtual DP_State DP_State { get; set; }
    }
}
