//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_CompanyStaffMapping
    {
        public int Id { get; set; }
        public string CompanyId { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<bool> Invitationstatus { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<byte> Status { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> StatusChangedate { get; set; }
        public Nullable<bool> IsMailSent { get; set; }
        public Nullable<System.DateTime> LastInvitationDate { get; set; }
    
        public virtual DP_User DP_User { get; set; }
    }
}
