//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_CommAnswers
    {
        public int Id { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public string Answer { get; set; }
        public Nullable<bool> IsCorrect { get; set; }
        public string Comment { get; set; }
        public Nullable<double> CorrectScore { get; set; }
        public Nullable<double> WrongScore { get; set; }
    
        public virtual DP_CommAssesment DP_CommAssesment { get; set; }
    }
}
