//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dp_CountyCity
    {
        public int Id { get; set; }
        public string Zip { get; set; }
        public string city { get; set; }
        public string State { get; set; }
        public string County { get; set; }
        public string areacode { get; set; }
        public string country { get; set; }
    }
}
