//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_CommLinks
    {
        public int Id { get; set; }
        public Nullable<int> DocMsgId { get; set; }
        public string LinkURL { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual DP_DocumentDetails DP_DocumentDetails { get; set; }
    }
}
