//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_CompanyPayment
    {
        public int Id { get; set; }
        public string CompanyId { get; set; }
        public string TransactionType { get; set; }
        public Nullable<double> AnnualLisenceFee { get; set; }
        public Nullable<int> NoOfPartners { get; set; }
        public Nullable<double> PerPartnerFee { get; set; }
        public Nullable<int> NoOfStaff { get; set; }
        public Nullable<double> PerStaffFee { get; set; }
        public Nullable<int> NoOfIC { get; set; }
        public Nullable<double> PerIcFee { get; set; }
        public Nullable<bool> IsInvoice { get; set; }
        public string BusinessName { get; set; }
        public string TransactionCode { get; set; }
        public string TransactionMessage { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string PayerEmail { get; set; }
        public string ReceiverEmail { get; set; }
        public Nullable<double> PayAmount { get; set; }
        public string PaymentDate { get; set; }
        public string Currency { get; set; }
        public string InviteeCompanyId { get; set; }
    }
}
