//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_CitysTest
    {
        public int Id { get; set; }
        public string City { get; set; }
        public string Stateabbre { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CountyId { get; set; }
    }
}
