//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_CommAssesment
    {
        public DP_CommAssesment()
        {
            this.DP_CommAnswers = new HashSet<DP_CommAnswers>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DocMsgId { get; set; }
        public string Question { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<DP_CommAnswers> DP_CommAnswers { get; set; }
        public virtual DP_DocumentDetails DP_DocumentDetails { get; set; }
    }
}
