//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_ConfigurationSetting
    {
        public int Id { get; set; }
        public Nullable<bool> IsVendor { get; set; }
        public Nullable<bool> IsClient { get; set; }
        public Nullable<bool> IsIC { get; set; }
        public Nullable<bool> IsCoverageArea { get; set; }
        public string CompanyId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsICBgCheckApply { get; set; }
        public Nullable<bool> IsStaffBgCheckApply { get; set; }
        public Nullable<bool> IsICLicenseApply { get; set; }
        public Nullable<bool> IsICAddCreApply { get; set; }
        public Nullable<bool> IsStaffAddCreApply { get; set; }
        public Nullable<bool> IsICInternalApply { get; set; }
        public Nullable<bool> IsStaffInternalApply { get; set; }
        public Nullable<bool> IsWebinarApply { get; set; }
        public Nullable<bool> IsScormApply { get; set; }
        public Nullable<bool> IsServices { get; set; }
        public Nullable<bool> IsClientOnMyProfile { get; set; }
        public Nullable<bool> IsCoverageAreaForIC { get; set; }
        public Nullable<bool> IsServicesForIC { get; set; }
        public Nullable<bool> IsICClientOnMyProfile { get; set; }
        public Nullable<bool> IsCoverageAreaForStaff { get; set; }
        public Nullable<bool> IsServicesForStaff { get; set; }
        public Nullable<bool> IsStaffClientOnMyProfile { get; set; }
        public Nullable<bool> IsLicenseForStaff { get; set; }
        public Nullable<bool> IsICFreeBasicMembership { get; set; }
        public Nullable<bool> IsICUsePackages { get; set; }
        public Nullable<bool> IsStaffInsApply { get; set; }
        public Nullable<bool> IsICInsApply { get; set; }
        public Nullable<bool> IsStaffCommApply { get; set; }
        public Nullable<bool> IsICCommApply { get; set; }
        public Nullable<bool> IsContractManagementApply { get; set; }
        public Nullable<bool> IsClientNameApplyForIC { get; set; }
    }
}
