//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_DocAssesment
    {
        public int Id { get; set; }
        public Nullable<int> DocId { get; set; }
        public string Question { get; set; }
        public string QuestionType { get; set; }
    
        public virtual DP_DocumentDetails DP_DocumentDetails { get; set; }
    }
}
