//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_Group
    {
        public DP_Group()
        {
            this.DP_Category = new HashSet<DP_Category>();
            this.DP_Reference = new HashSet<DP_Reference>();
        }
    
        public int Id { get; set; }
        public string Group { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CompanyId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ICollection<DP_Category> DP_Category { get; set; }
        public virtual ICollection<DP_Reference> DP_Reference { get; set; }
    }
}
