//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_InsuranceMapping
    {
        public DP_InsuranceMapping()
        {
            this.DP_InsuranceUploadDocs = new HashSet<DP_InsuranceUploadDocs>();
        }
    
        public int Id { get; set; }
        public Nullable<int> InsId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CompanyId { get; set; }
        public string PolicyNumber { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string Title { get; set; }
        public Nullable<double> SingleOccurance { get; set; }
        public Nullable<double> Aggregate { get; set; }
        public bool DocAndDataStatus { get; set; }
        public Nullable<System.DateTime> DocUploadedDate { get; set; }
        public string SterlingOrderId { get; set; }
    
        public virtual DP_InsuranceMaster DP_InsuranceMaster { get; set; }
        public virtual ICollection<DP_InsuranceUploadDocs> DP_InsuranceUploadDocs { get; set; }
    }
}
