//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_ICNonClientsMapping
    {
        public int Id { get; set; }
        public string InviteeCompanyId { get; set; }
        public Nullable<int> InviteeUserId { get; set; }
        public string InvitedCompanyId { get; set; }
        public Nullable<int> InvitedUserId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool IsActive { get; set; }
        public bool Invitationstatus { get; set; }
        public Nullable<System.DateTime> StatusChangeDate { get; set; }
        public Nullable<bool> IsMailSent { get; set; }
        public Nullable<System.DateTime> LastInvitationDate { get; set; }
        public byte Status { get; set; }
        public bool AllowToView { get; set; }
    
        public virtual DP_User DP_User { get; set; }
    }
}
