//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_InsuranceMaster
    {
        public DP_InsuranceMaster()
        {
            this.DP_InsuranceAck = new HashSet<DP_InsuranceAck>();
            this.DP_InsuranceMapping = new HashSet<DP_InsuranceMapping>();
            this.DP_InsuranceUploadDocs = new HashSet<DP_InsuranceUploadDocs>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ICTypeId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CompanyId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string CreatorCompanyId { get; set; }
        public string InsuranceType { get; set; }
        public string Source { get; set; }
        public string InsuranceVerType { get; set; }
    
        public virtual ICollection<DP_InsuranceAck> DP_InsuranceAck { get; set; }
        public virtual ICollection<DP_InsuranceMapping> DP_InsuranceMapping { get; set; }
        public virtual ICollection<DP_InsuranceUploadDocs> DP_InsuranceUploadDocs { get; set; }
    }
}
