//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_LicenseInsuranceReceiver
    {
        public int Id { get; set; }
        public Nullable<int> LicInsId { get; set; }
        public string CompanyName { get; set; }
        public string LicenseNumber { get; set; }
        public string PolicyNo { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string StateAbbre { get; set; }
        public Nullable<byte> IsCompleted { get; set; }
        public Nullable<bool> IsMailSend { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CompanyId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
    
        public virtual DP_LicenseInsuranceMaster DP_LicenseInsuranceMaster { get; set; }
    }
}
