//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_LicenseInsuranceMaster
    {
        public DP_LicenseInsuranceMaster()
        {
            this.DP_LicenseInsuranceAck = new HashSet<DP_LicenseInsuranceAck>();
            this.DP_LicenseInsuranceDocUpload = new HashSet<DP_LicenseInsuranceDocUpload>();
            this.DP_LicenseInsuranceReceiver = new HashSet<DP_LicenseInsuranceReceiver>();
            this.DP_LicenseInsuranceVendorType = new HashSet<DP_LicenseInsuranceVendorType>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<bool> IsExpiryDateReq { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CompanyId { get; set; }
        public Nullable<bool> IsCompanyNameReq { get; set; }
        public Nullable<bool> isLicenseNumberreq { get; set; }
        public Nullable<bool> isPolicyNumberReq { get; set; }
        public Nullable<bool> IsStatereq { get; set; }
        public Nullable<bool> Allowtoupload { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string ReqDocFor { get; set; }
        public Nullable<byte> ReqType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> VendorTypeId { get; set; }
        public Nullable<bool> IsElectronic { get; set; }
    
        public virtual ICollection<DP_LicenseInsuranceAck> DP_LicenseInsuranceAck { get; set; }
        public virtual ICollection<DP_LicenseInsuranceDocUpload> DP_LicenseInsuranceDocUpload { get; set; }
        public virtual ICollection<DP_LicenseInsuranceReceiver> DP_LicenseInsuranceReceiver { get; set; }
        public virtual ICollection<DP_LicenseInsuranceVendorType> DP_LicenseInsuranceVendorType { get; set; }
    }
}
