//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_MessagesReply
    {
        public int id { get; set; }
        public Nullable<int> ReplyFrom { get; set; }
        public Nullable<int> ReplyTo { get; set; }
        public string ReplyBody { get; set; }
        public Nullable<System.DateTime> ReplyDate { get; set; }
        public Nullable<int> MsgId { get; set; }
        public string ReplyStatus { get; set; }
        public Nullable<int> recipientid { get; set; }
    
        public virtual DP_MessagesDetails DP_MessagesDetails { get; set; }
        public virtual DP_User DP_User { get; set; }
        public virtual DP_User DP_User1 { get; set; }
        public virtual DP_Recipient DP_Recipient { get; set; }
    }
}
