//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_MailFooter
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        public string SignatureName { get; set; }
        public string Signature { get; set; }
    
        public virtual DP_User DP_User { get; set; }
    }
}
