//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_MessagesDetails
    {
        public DP_MessagesDetails()
        {
            this.DP_MessagesReply = new HashSet<DP_MessagesReply>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> ReqReplyDate { get; set; }
        public Nullable<bool> ReqiuredESign { get; set; }
        public string PPFile_Loc { get; set; }
        public string EmbededVideoCode { get; set; }
        public string MessageBody { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string MsgTitle { get; set; }
    
        public virtual ICollection<DP_MessagesReply> DP_MessagesReply { get; set; }
        public virtual DP_User DP_User { get; set; }
    }
}
