//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_ProfessionalLicenseMaster
    {
        public DP_ProfessionalLicenseMaster()
        {
            this.Dp_ProfessionalLicenseAck = new HashSet<Dp_ProfessionalLicenseAck>();
            this.DP_ProfessionalLicenseMapping = new HashSet<DP_ProfessionalLicenseMapping>();
            this.DP_ProfessionalLicenseUploadDocs = new HashSet<DP_ProfessionalLicenseUploadDocs>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ICTypeId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CompanyId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string CreatorCompanyId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string LicenseType { get; set; }
        public string Source { get; set; }
        public Nullable<bool> IsStaffTitle { get; set; }
    
        public virtual ICollection<Dp_ProfessionalLicenseAck> Dp_ProfessionalLicenseAck { get; set; }
        public virtual ICollection<DP_ProfessionalLicenseMapping> DP_ProfessionalLicenseMapping { get; set; }
        public virtual ICollection<DP_ProfessionalLicenseUploadDocs> DP_ProfessionalLicenseUploadDocs { get; set; }
    }
}
