//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_PayementMaster
    {
        public int Id { get; set; }
        public string CompanyCode { get; set; }
        public Nullable<double> CompanyFee { get; set; }
        public Nullable<double> PerFieldstaffFee { get; set; }
        public Nullable<double> PerOfficestaffFee { get; set; }
        public Nullable<double> PerICFee { get; set; }
        public bool IsInvoice { get; set; }
    }
}
