//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_ProfessionalLicenseMapping
    {
        public DP_ProfessionalLicenseMapping()
        {
            this.DP_ProfessionalLicenseUploadDocs = new HashSet<DP_ProfessionalLicenseUploadDocs>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProfLiceId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CompanyId { get; set; }
        public string Title { get; set; }
        public string LicenseNumber { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string Source { get; set; }
        public bool DocAndDataStatus { get; set; }
        public Nullable<System.DateTime> DocUploadedDate { get; set; }
        public string SterlingOrderId { get; set; }
    
        public virtual DP_ProfessionalLicenseMaster DP_ProfessionalLicenseMaster { get; set; }
        public virtual ICollection<DP_ProfessionalLicenseUploadDocs> DP_ProfessionalLicenseUploadDocs { get; set; }
    }
}
