//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_PermissionMaster
    {
        public DP_PermissionMaster()
        {
            this.DP_PermissionMapping = new HashSet<DP_PermissionMapping>();
        }
    
        public int Id { get; set; }
        public string Permission { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<DP_PermissionMapping> DP_PermissionMapping { get; set; }
    }
}
