//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_Profile
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Firstname { get; set; }
        public string MiddelName { get; set; }
        public string LastName { get; set; }
        public string Nickname { get; set; }
        public string BusinessName { get; set; }
        public string Website { get; set; }
        public string OfficePhone { get; set; }
        public string Address { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string CityName { get; set; }
        public string Direction { get; set; }
        public string StreetNumber { get; set; }
        public string Street { get; set; }
        public string ZipCode { get; set; }
        public string CellAreaCode { get; set; }
        public string CellNumber { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string CompanyLogo { get; set; }
        public string StaffListFile_Location { get; set; }
        public string UserType { get; set; }
        public string NoOfEmployee { get; set; }
        public string CompanyCAStatus { get; set; }
        public string UserCAStatus { get; set; }
        public Nullable<bool> IsPayment { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string profilephoto { get; set; }
        public byte ServicesStatus { get; set; }
        public Nullable<bool> IsClientApply { get; set; }
        public string BioInfo { get; set; }
        public string BusinessClass { get; set; }
        public string CertifyingAgency { get; set; }
        public string CertificationNumber { get; set; }
        public Nullable<System.DateTime> CertificateExpDate { get; set; }
    
        public virtual DP_User DP_User { get; set; }
    }
}
