//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dp_ProfessionalLicenseAck
    {
        public int Id { get; set; }
        public string Ackknow { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> ProfLicId { get; set; }
    
        public virtual DP_ProfessionalLicenseMaster DP_ProfessionalLicenseMaster { get; set; }
    }
}
