//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_PermissionTableMapping
    {
        public int Id { get; set; }
        public Nullable<int> TitleId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> FuntionalPermissionId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string CreatedCompanyId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
