//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_ProfessionalLicenseUploadDocs
    {
        public int Id { get; set; }
        public Nullable<int> ProfLicId { get; set; }
        public string DocLoc { get; set; }
        public Nullable<int> DocSeqNo { get; set; }
        public string CompanyId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProfLicMapId { get; set; }
        public Nullable<System.DateTime> DocUploadedDate { get; set; }
    
        public virtual DP_ProfessionalLicenseMapping DP_ProfessionalLicenseMapping { get; set; }
        public virtual DP_ProfessionalLicenseMaster DP_ProfessionalLicenseMaster { get; set; }
    }
}
