//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_Performance
    {
        public int PerformaneID { get; set; }
        public string DeliverCompanyID { get; set; }
        public int DeliveredUserID { get; set; }
        public int DocID { get; set; }
        public Nullable<int> TotalDocReceivedbystaff { get; set; }
        public Nullable<int> TotalDocCompletedbyStaf { get; set; }
        public Nullable<int> TotalDocReceivedbyVendor { get; set; }
        public Nullable<int> TotalDocCompletebyVendor { get; set; }
        public Nullable<int> TotalDocReceivedbyClient { get; set; }
        public Nullable<int> TotalDocCompletebyClient { get; set; }
        public Nullable<int> TotalDocReceivedbyDD { get; set; }
        public Nullable<int> TotalDocCompletebyDD { get; set; }
        public Nullable<int> TotalDocReceivedbyIC { get; set; }
        public Nullable<int> TotalDocCompletebyIC { get; set; }
    }
}
