//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_ReqDocAudit
    {
        public DP_ReqDocAudit()
        {
            this.DP_ReqDocAuditUpload = new HashSet<DP_ReqDocAuditUpload>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ReqDocReceiverId { get; set; }
        public Nullable<int> VisitorId { get; set; }
        public Nullable<int> AuditDocId { get; set; }
        public string CompanyName { get; set; }
        public string LicenseNumber { get; set; }
        public string PolicyNo { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string StateAbbre { get; set; }
        public Nullable<bool> IsDocUploaded { get; set; }
        public Nullable<byte> IsMarkAsComplete { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual ICollection<DP_ReqDocAuditUpload> DP_ReqDocAuditUpload { get; set; }
        public virtual DP_ReqDocReceiver DP_ReqDocReceiver { get; set; }
        public virtual DP_User DP_User { get; set; }
    }
}
