//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_ReqDocSender
    {
        public DP_ReqDocSender()
        {
            this.DP_ReqDocUpload = new HashSet<DP_ReqDocUpload>();
            this.DP_ReqDocService = new HashSet<DP_ReqDocService>();
            this.DP_ReqDocVendorType = new HashSet<DP_ReqDocVendorType>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<bool> IsExpiryDateReq { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CompanyId { get; set; }
        public Nullable<bool> IsCompanyNameReq { get; set; }
        public Nullable<bool> isLicenseNumberreq { get; set; }
        public Nullable<bool> isPolicyNumberReq { get; set; }
        public Nullable<bool> IsStatereq { get; set; }
        public Nullable<bool> Allowtoupload { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string ReqDocFor { get; set; }
        public Nullable<byte> ReqType { get; set; }
        public Nullable<bool> DNA { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string Retake { get; set; }
    
        public virtual ICollection<DP_ReqDocUpload> DP_ReqDocUpload { get; set; }
        public virtual ICollection<DP_ReqDocService> DP_ReqDocService { get; set; }
        public virtual ICollection<DP_ReqDocVendorType> DP_ReqDocVendorType { get; set; }
    }
}
