//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_ReqiureDocument
    {
        public int Id { get; set; }
        public string DocumentLocation { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> IsRequired { get; set; }
    
        public virtual DP_User DP_User { get; set; }
    }
}
