//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_ReqDocVendorType
    {
        public int Id { get; set; }
        public Nullable<int> VendorTypeId { get; set; }
        public Nullable<int> ReqDocId { get; set; }
    
        public virtual DP_ReqDocSender DP_ReqDocSender { get; set; }
        public virtual DP_VendorType DP_VendorType { get; set; }
    }
}
