//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_Recipient
    {
        public int Id { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<int> MsgId { get; set; }
        public Nullable<int> DocId { get; set; }
        public Nullable<int> RecipientUserId { get; set; }
        public Nullable<bool> MoveInHistory { get; set; }
        public Nullable<int> DeliveredUserId { get; set; }
        public string MsgDocStatus { get; set; }
        public Nullable<bool> Accepted { get; set; }
        public string Assessmentresult { get; set; }
        public string Type { get; set; }
        public string Timespend { get; set; }
        public Nullable<int> DocSeqNo { get; set; }
        public Nullable<int> VersionNo { get; set; }
        public Nullable<System.DateTime> ArchiveDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Withdrawndate { get; set; }
        public string UserType { get; set; }
        public Nullable<System.DateTime> RecipeintDueDate { get; set; }
        public bool IsmailSend { get; set; }
        public string DeliveredCompanyId { get; set; }
        public string RecipientCompanyid { get; set; }
        public bool IsRetake { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsUpdatePerformance { get; set; }
        public Nullable<System.DateTime> CommReceivedDate { get; set; }
        public string WithdrwanBy { get; set; }
    }
}
