//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    
    public partial class DP_StaffPerformance_Result1
    {
        public Nullable<int> StaffId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Total { get; set; }
        public string Title { get; set; }
        public Nullable<int> Completed { get; set; }
    }
}
