//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_State
    {
        public DP_State()
        {
            this.DP_City = new HashSet<DP_City>();
            this.DP_County = new HashSet<DP_County>();
        }
    
        public int Id { get; set; }
        public string State { get; set; }
        public string StateAbbre { get; set; }
        public Nullable<double> DriverLicenseCost { get; set; }
    
        public virtual ICollection<DP_City> DP_City { get; set; }
        public virtual ICollection<DP_County> DP_County { get; set; }
    }
}
