//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_SkillSetMaster
    {
        public DP_SkillSetMaster()
        {
            this.DP_SkillSetMapping = new HashSet<DP_SkillSetMapping>();
        }
    
        public int Id { get; set; }
        public string SkillSet { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<DP_SkillSetMapping> DP_SkillSetMapping { get; set; }
    }
}
