//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_SterlingScreeningMapping
    {
        public int Id { get; set; }
        public string UniqueRequestId { get; set; }
        public string ScreenType { get; set; }
        public string ScreenQualifier { get; set; }
        public string ScreenClientRefId { get; set; }
        public string ScreenOrderStatus { get; set; }
        public string ScreenResultStatus { get; set; }
        public string ScreenOpenDate { get; set; }
        public string ScreenCloseDate { get; set; }
        public string ScreenResultText { get; set; }
    }
}
