//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_User
    {
        public DP_User()
        {
            this.DP_Announcement = new HashSet<DP_Announcement>();
            this.DP_ComapnyVendorMapping = new HashSet<DP_ComapnyVendorMapping>();
            this.DP_CompanyStaffMapping = new HashSet<DP_CompanyStaffMapping>();
            this.DP_DocFlowMapping = new HashSet<DP_DocFlowMapping>();
            this.DP_DocumentDetails = new HashSet<DP_DocumentDetails>();
            this.DP_EmailTrakingDetails = new HashSet<DP_EmailTrakingDetails>();
            this.DP_FlowMapping = new HashSet<DP_FlowMapping>();
            this.DP_ICNonClientsMapping = new HashSet<DP_ICNonClientsMapping>();
            this.DP_License = new HashSet<DP_License>();
            this.DP_MailFooter = new HashSet<DP_MailFooter>();
            this.DP_PermissionMapping = new HashSet<DP_PermissionMapping>();
            this.DP_Profile = new HashSet<DP_Profile>();
            this.DP_RecurringPayment = new HashSet<DP_RecurringPayment>();
            this.DP_ReqDocAudit = new HashSet<DP_ReqDocAudit>();
            this.DP_RoleMapping = new HashSet<DP_RoleMapping>();
            this.DP_TitleMapping = new HashSet<DP_TitleMapping>();
            this.DP_VerfiedLicenseDetails = new HashSet<DP_VerfiedLicenseDetails>();
            this.DP_VendorTypeMapping = new HashSet<DP_VendorTypeMapping>();
            this.DP_WebinarOrganiserMaster = new HashSet<DP_WebinarOrganiserMaster>();
            this.DP_Welcome = new HashSet<DP_Welcome>();
        }
    
        public int Id { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public Nullable<int> Question1 { get; set; }
        public Nullable<int> Question2 { get; set; }
        public Nullable<int> Question3 { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Answer1 { get; set; }
        public string Answer2 { get; set; }
        public string Answer3 { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> IsTemp { get; set; }
        public string UserId { get; set; }
        public string CompanyId { get; set; }
        public bool IsRegistered { get; set; }
        public Nullable<System.DateTime> RegisteredDate { get; set; }
    
        public virtual ICollection<DP_Announcement> DP_Announcement { get; set; }
        public virtual ICollection<DP_ComapnyVendorMapping> DP_ComapnyVendorMapping { get; set; }
        public virtual ICollection<DP_CompanyStaffMapping> DP_CompanyStaffMapping { get; set; }
        public virtual ICollection<DP_DocFlowMapping> DP_DocFlowMapping { get; set; }
        public virtual ICollection<DP_DocumentDetails> DP_DocumentDetails { get; set; }
        public virtual ICollection<DP_EmailTrakingDetails> DP_EmailTrakingDetails { get; set; }
        public virtual ICollection<DP_FlowMapping> DP_FlowMapping { get; set; }
        public virtual ICollection<DP_ICNonClientsMapping> DP_ICNonClientsMapping { get; set; }
        public virtual ICollection<DP_License> DP_License { get; set; }
        public virtual ICollection<DP_MailFooter> DP_MailFooter { get; set; }
        public virtual ICollection<DP_PermissionMapping> DP_PermissionMapping { get; set; }
        public virtual ICollection<DP_Profile> DP_Profile { get; set; }
        public virtual ICollection<DP_RecurringPayment> DP_RecurringPayment { get; set; }
        public virtual ICollection<DP_ReqDocAudit> DP_ReqDocAudit { get; set; }
        public virtual ICollection<DP_RoleMapping> DP_RoleMapping { get; set; }
        public virtual DP_Security DP_Security { get; set; }
        public virtual ICollection<DP_TitleMapping> DP_TitleMapping { get; set; }
        public virtual ICollection<DP_VerfiedLicenseDetails> DP_VerfiedLicenseDetails { get; set; }
        public virtual ICollection<DP_VendorTypeMapping> DP_VendorTypeMapping { get; set; }
        public virtual ICollection<DP_WebinarOrganiserMaster> DP_WebinarOrganiserMaster { get; set; }
        public virtual ICollection<DP_Welcome> DP_Welcome { get; set; }
    }
}
