//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_VerfiedLicenseDetails
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CompanyId { get; set; }
        public string LicenseNumber { get; set; }
        public string LicenseType { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string PhoneNumber { get; set; }
        public string StateAbbre { get; set; }
        public string City { get; set; }
        public string County_Code { get; set; }
        public string Zip { get; set; }
    
        public virtual DP_User DP_User { get; set; }
    }
}
