//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointDAL.Repository
{
    using System;
    
    public partial class USP_UserView_Result2
    {
        public string Name { get; set; }
        public string BusinessName { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string DocType { get; set; }
        public string Status { get; set; }
        public string Reference { get; set; }
        public string UserTitle { get; set; }
        public string introduction { get; set; }
        public string DocTitles { get; set; }
        public string VideoTitle { get; set; }
        public string ScormTitles { get; set; }
        public string FileTitle { get; set; }
        public string Filetype { get; set; }
        public string FileLoc { get; set; }
    }
}
