//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DecisionPoint_EE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DecisionPoint_EE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DecisionPoint_EE", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string colon {
            get {
                return ResourceManager.GetString("colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to completed.
        /// </summary>
        internal static string completed {
            get {
                return ResourceManager.GetString("completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password Required..
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Correct Email Id..
        /// </summary>
        internal static string CorrectEmailId {
            get {
                return ResourceManager.GetString("CorrectEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Column header not match..
        /// </summary>
        internal static string CsvHeaderNotMatch {
            get {
                return ResourceManager.GetString("CsvHeaderNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Column not match..
        /// </summary>
        internal static string CsvNotMatch {
            get {
                return ResourceManager.GetString("CsvNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Already Exists..
        /// </summary>
        internal static string EmailExist {
            get {
                return ResourceManager.GetString("EmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id Not Matched..
        /// </summary>
        internal static string EmailNotMatch {
            get {
                return ResourceManager.GetString("EmailNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Required..
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        internal static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name Required.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC.
        /// </summary>
        internal static string IC {
            get {
                return ResourceManager.GetString("IC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incomming.
        /// </summary>
        internal static string incomming {
            get {
                return ResourceManager.GetString("incomming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        internal static string IncorrectPswd {
            get {
                return ResourceManager.GetString("IncorrectPswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Upload CSV Format File..
        /// </summary>
        internal static string InvalidCsvFormat {
            get {
                return ResourceManager.GetString("InvalidCsvFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email or Old Password..
        /// </summary>
        internal static string InvalidEmailOldPswd {
            get {
                return ResourceManager.GetString("InvalidEmailOldPswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        internal static string InvalidUserNamePassword {
            get {
                return ResourceManager.GetString("InvalidUserNamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incoming.
        /// </summary>
        internal static string InviteFilterIncoming {
            get {
                return ResourceManager.GetString("InviteFilterIncoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outgoing.
        /// </summary>
        internal static string InviteFilteroutgoing {
            get {
                return ResourceManager.GetString("InviteFilteroutgoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removed.
        /// </summary>
        internal static string InviteFilterremoved {
            get {
                return ResourceManager.GetString("InviteFilterremoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name Required.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted Successfully...
        /// </summary>
        internal static string MailfooterInserted {
            get {
                return ResourceManager.GetString("MailfooterInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully...
        /// </summary>
        internal static string MailfooterUpdated {
            get {
                return ResourceManager.GetString("MailfooterUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mycommunication.
        /// </summary>
        internal static string mycommunication {
            get {
                return ResourceManager.GetString("mycommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Not Done..
        /// </summary>
        internal static string NoPayment {
            get {
                return ResourceManager.GetString("NoPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Not Changed..
        /// </summary>
        internal static string NotChangedPswd {
            get {
                return ResourceManager.GetString("NotChangedPswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Not Done..
        /// </summary>
        internal static string NotRegistered {
            get {
                return ResourceManager.GetString("NotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Not Matched.
        /// </summary>
        internal static string PaaswordNotMatch {
            get {
                return ResourceManager.GetString("PaaswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password minimum length should be 6 character..
        /// </summary>
        internal static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password should not match with old password..
        /// </summary>
        internal static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should be alphanumeric with one special character..
        /// </summary>
        internal static string PasswordRules {
            get {
                return ResourceManager.GetString("PasswordRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Sent To Your Email..
        /// </summary>
        internal static string PasswordSent {
            get {
                return ResourceManager.GetString("PasswordSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Sucessfull..
        /// </summary>
        internal static string PaymentSuccess {
            get {
                return ResourceManager.GetString("PaymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password Required..
        /// </summary>
        internal static string RequireNewPassword {
            get {
                return ResourceManager.GetString("RequireNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password Required..
        /// </summary>
        internal static string RequireOldPassword {
            get {
                return ResourceManager.GetString("RequireOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Required..
        /// </summary>
        internal static string RequirePassword {
            get {
                return ResourceManager.GetString("RequirePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to staffcommunication.
        /// </summary>
        internal static string staffcommunication {
            get {
                return ResourceManager.GetString("staffcommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Upload CSV File..
        /// </summary>
        internal static string UploadCsv {
            get {
                return ResourceManager.GetString("UploadCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this Email not exists..
        /// </summary>
        internal static string UserExists {
            get {
                return ResourceManager.GetString("UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WithID.
        /// </summary>
        internal static string WithID {
            get {
                return ResourceManager.GetString("WithID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WithoutID.
        /// </summary>
        internal static string WithoutID {
            get {
                return ResourceManager.GetString("WithoutID", resourceCulture);
            }
        }
    }
}
