//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionPointCAL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DecisionPointR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DecisionPointR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DecisionPointCAL.DecisionPointR", typeof(DecisionPointR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accecptedI.
        /// </summary>
        public static string accecptedI {
            get {
                return ResourceManager.GetString("accecptedI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accecptedO.
        /// </summary>
        public static string accecptedO {
            get {
                return ResourceManager.GetString("accecptedO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string APIAddProductMsg1 {
            get {
                return ResourceManager.GetString("APIAddProductMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub client not found.
        /// </summary>
        public static string APIAddProductMsg2 {
            get {
                return ResourceManager.GetString("APIAddProductMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client not found.
        /// </summary>
        public static string APIAddProductMsg3 {
            get {
                return ResourceManager.GetString("APIAddProductMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found for client .
        /// </summary>
        public static string APIAddProductMsg4 {
            get {
                return ResourceManager.GetString("APIAddProductMsg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string astrik {
            get {
                return ResourceManager.GetString("astrik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt;.
        /// </summary>
        public static string BreakLineTag {
            get {
                return ResourceManager.GetString("BreakLineTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 403 Forbidden response should be used afterwards, when the user is authenticated but is not authorized to perform the requested operation on the given resource.
        /// </summary>
        public static string BrowserRequestMessage {
            get {
                return ResourceManager.GetString("BrowserRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client.
        /// </summary>
        public static string client {
            get {
                return ResourceManager.GetString("client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client and investors/servicers requirements met.
        /// </summary>
        public static string ClientAndInvestorMeet {
            get {
                return ResourceManager.GetString("ClientAndInvestorMeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #c6efcd.
        /// </summary>
        public static string ClientAndInvestorMeetColor {
            get {
                return ResourceManager.GetString("ClientAndInvestorMeetColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client requirements met – not all investor/servicers requirements met.
        /// </summary>
        public static string ClientMeetInvestorNotMeet {
            get {
                return ResourceManager.GetString("ClientMeetInvestorNotMeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Feeb9e.
        /// </summary>
        public static string ClientMeetInvestorNotMeetColor {
            get {
                return ResourceManager.GetString("ClientMeetInvestorNotMeetColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client requirements not met.
        /// </summary>
        public static string ClientNotMeetAndInvestorNotMeet {
            get {
                return ResourceManager.GetString("ClientNotMeetAndInvestorNotMeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ffc8ce.
        /// </summary>
        public static string ClientNotMeetAndInvestorNotMeetColor {
            get {
                return ResourceManager.GetString("ClientNotMeetAndInvestorNotMeetColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _CmpLogo.
        /// </summary>
        public static string CmpLogo {
            get {
                return ResourceManager.GetString("CmpLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        public static string colon {
            get {
                return ResourceManager.GetString("colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Complete State).
        /// </summary>
        public static string ComleteStateTitle {
            get {
                return ResourceManager.GetString("ComleteStateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        public static string comma {
            get {
                return ResourceManager.GetString("comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Complete County).
        /// </summary>
        public static string CompleteCountyTitle {
            get {
                return ResourceManager.GetString("CompleteCountyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to completed.
        /// </summary>
        public static string completed {
            get {
                return ResourceManager.GetString("completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compliance Manager.
        /// </summary>
        public static string ComplianceManager {
            get {
                return ResourceManager.GetString("ComplianceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password Required..
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content type should be in text/xml.
        /// </summary>
        public static string ContentTypeNotMatchMsg {
            get {
                return ResourceManager.GetString("ContentTypeNotMatchMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Correct Email Id..
        /// </summary>
        public static string CorrectEmailId {
            get {
                return ResourceManager.GetString("CorrectEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Column header not match..
        /// </summary>
        public static string CsvHeaderNotMatch {
            get {
                return ResourceManager.GetString("CsvHeaderNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Column not match..
        /// </summary>
        public static string CsvNotMatch {
            get {
                return ResourceManager.GetString("CsvNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to denyI.
        /// </summary>
        public static string denyI {
            get {
                return ResourceManager.GetString("denyI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to denyO.
        /// </summary>
        public static string denyO {
            get {
                return ResourceManager.GetString("denyO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Already Exists..
        /// </summary>
        public static string EmailExist {
            get {
                return ResourceManager.GetString("EmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id Not Matched..
        /// </summary>
        public static string EmailNotMatch {
            get {
                return ResourceManager.GetString("EmailNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Required..
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Received.
        /// </summary>
        public static string EntityIdentifierMessage {
            get {
                return ResourceManager.GetString("EntityIdentifierMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wronge in error message..
        /// </summary>
        public static string Errorlbl {
            get {
                return ResourceManager.GetString("Errorlbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested URL could not be retrieved.
        /// </summary>
        public static string ErrorPageMsg1 {
            get {
                return ResourceManager.GetString("ErrorPageMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error was encountered while trying to retrieve the URL.
        /// </summary>
        public static string ErrorPageMsg2 {
            get {
                return ResourceManager.GetString("ErrorPageMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue in XML File.
        /// </summary>
        public static string ExceptionMsg {
            get {
                return ResourceManager.GetString("ExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fail.
        /// </summary>
        public static string failinsmall {
            get {
                return ResourceManager.GetString("failinsmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name Required.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forward.
        /// </summary>
        public static string forward {
            get {
                return ResourceManager.GetString("forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getcompanyid.
        /// </summary>
        public static string getcompanyid {
            get {
                return ResourceManager.GetString("getcompanyid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to history.
        /// </summary>
        public static string history {
            get {
                return ResourceManager.GetString("history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC.
        /// </summary>
        public static string IC {
            get {
                return ResourceManager.GetString("IC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICListWithID.csv.
        /// </summary>
        public static string ICListWithID {
            get {
                return ResourceManager.GetString("ICListWithID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICListWithoutID.csv.
        /// </summary>
        public static string ICListWithoutID {
            get {
                return ResourceManager.GetString("ICListWithoutID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDenied.
        /// </summary>
        public static string IDenied {
            get {
                return ResourceManager.GetString("IDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incomming.
        /// </summary>
        public static string incomming {
            get {
                return ResourceManager.GetString("incomming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string IncorrectPswd {
            get {
                return ResourceManager.GetString("IncorrectPswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Upload CSV Format File..
        /// </summary>
        public static string InvalidCsvFormat {
            get {
                return ResourceManager.GetString("InvalidCsvFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email or Old Password..
        /// </summary>
        public static string InvalidEmailOldPswd {
            get {
                return ResourceManager.GetString("InvalidEmailOldPswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string InvalidUserNamePassword {
            get {
                return ResourceManager.GetString("InvalidUserNamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incoming.
        /// </summary>
        public static string InviteFilterIncoming {
            get {
                return ResourceManager.GetString("InviteFilterIncoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outgoing.
        /// </summary>
        public static string InviteFilteroutgoing {
            get {
                return ResourceManager.GetString("InviteFilteroutgoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removed.
        /// </summary>
        public static string InviteFilterremoved {
            get {
                return ResourceManager.GetString("InviteFilterremoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt;Subject: Compliance Tracker Account&lt;br/&gt;&lt;br/&gt;.
        /// </summary>
        public static string InviteMailBodyForSAndICMsg1 {
            get {
                return ResourceManager.GetString("InviteMailBodyForSAndICMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  welcome to Compliance Tracker.Below you will find your username and a temporary password to gain access to the application. With Compliance Tracker you will be able to access and read all your company’s policy and procedures, directives, e-learning and much more! You also get a library where all the documents and e-learning are stored for your easy reference.Log in, reset you temporary password and complete your profile.If you have any trouble please feel free to contact your system administrator.&lt;br/&gt;&lt;br/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InviteMailBodyForSAndICMsg2 {
            get {
                return ResourceManager.GetString("InviteMailBodyForSAndICMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;&gt;click here&lt;/a&gt; to get to log in page&lt;/br&gt;&lt;br/&gt;User Name:.
        /// </summary>
        public static string InviteMailBodyForSAndICMsg3 {
            get {
                return ResourceManager.GetString("InviteMailBodyForSAndICMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt;Subject: Compliance Tracker&lt;br/&gt;&lt;br/&gt;.
        /// </summary>
        public static string InviteMailBodyForVendorAndClientMsg1 {
            get {
                return ResourceManager.GetString("InviteMailBodyForVendorAndClientMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has requested to join Compliance Tracker. Compliance Tracker is first industry wide tool that was  born out of federal regulations requiring that we can communicate state, federal, client and .
        /// </summary>
        public static string InviteMailBodyForVendorAndClientMsg2 {
            get {
                return ResourceManager.GetString("InviteMailBodyForVendorAndClientMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ’s best practices, policies and procedures to everyone relevant to process down to the ‘boots on the street’ and be able to provide an audit trail.&lt;br/&gt;&lt;br/&gt; Please &lt;a href=&apos;.
        /// </summary>
        public static string InviteMailBodyForVendorAndClientMsg3 {
            get {
                return ResourceManager.GetString("InviteMailBodyForVendorAndClientMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;&gt;click here&lt;/a&gt; to get to log in page&lt;/br&gt;&lt;br/&gt;User Name:.
        /// </summary>
        public static string InviteMailBodyForVendorAndClientMsg4 {
            get {
                return ResourceManager.GetString("InviteMailBodyForVendorAndClientMsg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&apos;line-height:25px&apos;&gt;To: .
        /// </summary>
        public static string InviteMailBodyMsg1 {
            get {
                return ResourceManager.GetString("InviteMailBodyMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt;From: .
        /// </summary>
        public static string InviteMailBodyMsg2 {
            get {
                return ResourceManager.GetString("InviteMailBodyMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt; Password: .
        /// </summary>
        public static string InviteMailBodyMsg3 {
            get {
                return ResourceManager.GetString("InviteMailBodyMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt;&lt;br/&gt;&lt;/br&gt;&lt;/br&gt;.
        /// </summary>
        public static string InviteMailBodyMsg4 {
            get {
                return ResourceManager.GetString("InviteMailBodyMsg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/div&gt;.
        /// </summary>
        public static string InviteMailBodyMsg5 {
            get {
                return ResourceManager.GetString("InviteMailBodyMsg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?id=.
        /// </summary>
        public static string InviteMailBodyMsg6 {
            get {
                return ResourceManager.GetString("InviteMailBodyMsg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compliance Tracker Account.
        /// </summary>
        public static string InviteMailSubjectForStaffAndIC {
            get {
                return ResourceManager.GetString("InviteMailSubjectForStaffAndIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compliance Tracker.
        /// </summary>
        public static string InviteMailSubjectForVendorAndClient {
            get {
                return ResourceManager.GetString("InviteMailSubjectForVendorAndClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation send sucessfully.
        /// </summary>
        public static string inviteSentSucessfullMsg {
            get {
                return ResourceManager.GetString("inviteSentSucessfullMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IOAccepted.
        /// </summary>
        public static string IOAccepted {
            get {
                return ResourceManager.GetString("IOAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IReceived.
        /// </summary>
        public static string IReceived {
            get {
                return ResourceManager.GetString("IReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name Required.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : {0}\n By : {1}-{2}.
        /// </summary>
        public static string logmessageerror {
            get {
                return ResourceManager.GetString("logmessageerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End {0} function..
        /// </summary>
        public static string logmessagend {
            get {
                return ResourceManager.GetString("logmessagend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Called {2} function ::{0} {1}..
        /// </summary>
        public static string logmessagestart {
            get {
                return ResourceManager.GetString("logmessagestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted Successfully...
        /// </summary>
        public static string MailfooterInserted {
            get {
                return ResourceManager.GetString("MailfooterInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully...
        /// </summary>
        public static string MailfooterUpdated {
            get {
                return ResourceManager.GetString("MailfooterUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        public static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mycommunication.
        /// </summary>
        public static string mycommunication {
            get {
                return ResourceManager.GetString("mycommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This communication exist in your Inbox.please review this communication and forward to staff..
        /// </summary>
        public static string MyDashBoardAdminMsg1 {
            get {
                return ResourceManager.GetString("MyDashBoardAdminMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pending invites please review these invites..
        /// </summary>
        public static string MyDashBoardAdminMsg2 {
            get {
                return ResourceManager.GetString("MyDashBoardAdminMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are.
        /// </summary>
        public static string MyDashBoardAdminMsg3 {
            get {
                return ResourceManager.GetString("MyDashBoardAdminMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to staff members that have not completed their registration..
        /// </summary>
        public static string MyDashBoardAdminMsg4 {
            get {
                return ResourceManager.GetString("MyDashBoardAdminMsg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC&apos;s who have not accepted their invitation..
        /// </summary>
        public static string MyDashBoardAdminMsg5 {
            get {
                return ResourceManager.GetString("MyDashBoardAdminMsg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vendor/client who have not accepted their invitation..
        /// </summary>
        public static string MyDashBoardAdminMsg6 {
            get {
                return ResourceManager.GetString("MyDashBoardAdminMsg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you get invites from.
        /// </summary>
        public static string MyDashBoardAdminMsg7 {
            get {
                return ResourceManager.GetString("MyDashBoardAdminMsg7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review this communication.
        /// </summary>
        public static string MyDashBoardCommunicationMsg1 {
            get {
                return ResourceManager.GetString("MyDashBoardCommunicationMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to it&apos;s due date is.
        /// </summary>
        public static string MyDashBoardCommunicationMsg2 {
            get {
                return ResourceManager.GetString("MyDashBoardCommunicationMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to due date is nothing.
        /// </summary>
        public static string MyDashBoardCommunicationMsg3 {
            get {
                return ResourceManager.GetString("MyDashBoardCommunicationMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract created by.
        /// </summary>
        public static string MyDashBoardContractMsg1 {
            get {
                return ResourceManager.GetString("MyDashBoardContractMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to going to expire on.
        /// </summary>
        public static string MyDashBoardContractMsg2 {
            get {
                return ResourceManager.GetString("MyDashBoardContractMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been expired on .
        /// </summary>
        public static string MyDashBoardContractMsg3 {
            get {
                return ResourceManager.GetString("MyDashBoardContractMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to going to expire today .
        /// </summary>
        public static string MyDashBoardContractMsg4 {
            get {
                return ResourceManager.GetString("MyDashBoardContractMsg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is.
        /// </summary>
        public static string MyDashBoardCoplianceMsg1 {
            get {
                return ResourceManager.GetString("MyDashBoardCoplianceMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to communication need to be completed by staff..
        /// </summary>
        public static string MyDashBoardCoplianceMsg2 {
            get {
                return ResourceManager.GetString("MyDashBoardCoplianceMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to communication need to be completed by ic..
        /// </summary>
        public static string MyDashBoardCoplianceMsg3 {
            get {
                return ResourceManager.GetString("MyDashBoardCoplianceMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to communication need to be completed by vendor..
        /// </summary>
        public static string MyDashBoardCoplianceMsg4 {
            get {
                return ResourceManager.GetString("MyDashBoardCoplianceMsg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to communication need to be completed by client..
        /// </summary>
        public static string MyDashBoardCoplianceMsg5 {
            get {
                return ResourceManager.GetString("MyDashBoardCoplianceMsg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the.
        /// </summary>
        public static string MyDashBoardMyProfileMsg1 {
            get {
                return ResourceManager.GetString("MyDashBoardMyProfileMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please added at least one.
        /// </summary>
        public static string MyDashBoardMyProfileMsg2 {
            get {
                return ResourceManager.GetString("MyDashBoardMyProfileMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in company.
        /// </summary>
        public static string MyDashBoardMyProfileMsg3 {
            get {
                return ResourceManager.GetString("MyDashBoardMyProfileMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have.
        /// </summary>
        public static string MyDashBoardMyProfileMsg4 {
            get {
                return ResourceManager.GetString("MyDashBoardMyProfileMsg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incompleted job compliance reqiurements.please review these..
        /// </summary>
        public static string MyDashBoardMyProfileMsg5 {
            get {
                return ResourceManager.GetString("MyDashBoardMyProfileMsg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Alerts !.
        /// </summary>
        public static string MyDashBoardNoAlertMsg {
            get {
                return ResourceManager.GetString("MyDashBoardNoAlertMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job requirements of .
        /// </summary>
        public static string MyProfileOutstandingActionMsg1 {
            get {
                return ResourceManager.GetString("MyProfileOutstandingActionMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is pending, please review it..
        /// </summary>
        public static string MyProfileOutstandingActionMsg2 {
            get {
                return ResourceManager.GetString("MyProfileOutstandingActionMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in license and insurance section.
        /// </summary>
        public static string MyProfileOutstandingActionMsg3 {
            get {
                return ResourceManager.GetString("MyProfileOutstandingActionMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Member.
        /// </summary>
        public static string NonMember {
            get {
                return ResourceManager.GetString("NonMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Not Done..
        /// </summary>
        public static string NoPayment {
            get {
                return ResourceManager.GetString("NoPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Not Changed..
        /// </summary>
        public static string NotChangedPswd {
            get {
                return ResourceManager.GetString("NotChangedPswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Not Done..
        /// </summary>
        public static string NotRegistered {
            get {
                return ResourceManager.GetString("NotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPending.
        /// </summary>
        public static string OPending {
            get {
                return ResourceManager.GetString("OPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Not Matched.
        /// </summary>
        public static string PaaswordNotMatch {
            get {
                return ResourceManager.GetString("PaaswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is some issue in requested url. Please contact to admin person..
        /// </summary>
        public static string PageErrorMsg {
            get {
                return ResourceManager.GetString("PageErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        public static string pass {
            get {
                return ResourceManager.GetString("pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pass.
        /// </summary>
        public static string passinsmall {
            get {
                return ResourceManager.GetString("passinsmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password minimum length should be 6 character..
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password should not match with old password..
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should be alphanumeric with one special character..
        /// </summary>
        public static string PasswordRules {
            get {
                return ResourceManager.GetString("PasswordRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Sent To Your Email..
        /// </summary>
        public static string PasswordSent {
            get {
                return ResourceManager.GetString("PasswordSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Sucessfull..
        /// </summary>
        public static string PaymentSuccess {
            get {
                return ResourceManager.GetString("PaymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pendingO.
        /// </summary>
        public static string pendingO {
            get {
                return ResourceManager.GetString("pendingO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results Processed.
        /// </summary>
        public static string processingTimestampNodeAttributeValue {
            get {
                return ResourceManager.GetString("processingTimestampNodeAttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to receivedI.
        /// </summary>
        public static string receivedI {
            get {
                return ResourceManager.GetString("receivedI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password Required..
        /// </summary>
        public static string RequireNewPassword {
            get {
                return ResourceManager.GetString("RequireNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password Required..
        /// </summary>
        public static string RequireOldPassword {
            get {
                return ResourceManager.GetString("RequireOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Required..
        /// </summary>
        public static string RequirePassword {
            get {
                return ResourceManager.GetString("RequirePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service.
        /// </summary>
        public static string service {
            get {
                return ResourceManager.GetString("service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to staffcommunication.
        /// </summary>
        public static string staffcommunication {
            get {
                return ResourceManager.GetString("staffcommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sterling001.
        /// </summary>
        public static string SterlingPassword {
            get {
                return ResourceManager.GetString("SterlingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review your .
        /// </summary>
        public static string SterlingResAction1 {
            get {
                return ResourceManager.GetString("SterlingResAction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  result..
        /// </summary>
        public static string SterlingResAction2 {
            get {
                return ResourceManager.GetString("SterlingResAction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string SterlingResSubject {
            get {
                return ResourceManager.GetString("SterlingResSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ST.
        /// </summary>
        public static string SterlingUserName {
            get {
                return ResourceManager.GetString("SterlingUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Category.
        /// </summary>
        public static string SubCategory {
            get {
                return ResourceManager.GetString("SubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperAdmin.
        /// </summary>
        public static string SuperAdmin {
            get {
                return ResourceManager.GetString("SuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string trueval {
            get {
                return ResourceManager.GetString("trueval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _.
        /// </summary>
        public static string underscore {
            get {
                return ResourceManager.GetString("underscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Upload CSV File..
        /// </summary>
        public static string UploadCsv {
            get {
                return ResourceManager.GetString("UploadCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email ID does not exist in our records..
        /// </summary>
        public static string UserExists {
            get {
                return ResourceManager.GetString("UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vendor.
        /// </summary>
        public static string vendor {
            get {
                return ResourceManager.GetString("vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WithID.
        /// </summary>
        public static string WithID {
            get {
                return ResourceManager.GetString("WithID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WithoutID.
        /// </summary>
        public static string WithoutID {
            get {
                return ResourceManager.GetString("WithoutID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
    }
}
